import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/navigation/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thomas Gonthier | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center mx-auto bg-[url('../../public/bg_light.svg')] dark:bg-[url('../../public/bg_dark.svg')] bg-cover bg-no-repeat text-usual-950 dark:text-usual-100 min-h-screen w-full relative`}>{children}</body>
    </html>
  );
}
