import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Thomas Gonthier | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fr'>
      <body className={`${inter.className} flex flex-col items-center mx-auto bg-[url('../../public/bg_light.svg')] dark:bg-[url('../../public/bg_dark.svg')] bg-cover bg-no-repeat text-usual-950 dark:text-usual-100 min-h-screen w-full relative`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          {/* <NextIntlClientProvider messages={messages}> */}
          {children}
          <Toaster />
          {/* </NextIntlClientProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
